.PHONY: secrets
secrets:
	@openssl req -x509 -newkey rsa:2048 -nodes -keyout secrets/server.key -out secrets/server.pem -days 365 -batch

FLAGS += -I liquid -use-menhir -plugin-tag "package(js_of_ocaml.ocamlbuild)"

# We don't want the camlp4 syntax extensions, so we define a
# CLIENT_BUILD separate from BUILD
CLIENT_BUILD = ocamlbuild -use-ocamlfind $(LIBS) $(FLAGS)

client::
	$(CLIENT_BUILD) client.js
